### ISSUE TITLE
Blayoppta

### ISSUE THREAD

**Issue by DonnieDrummer** [DonnieDrummer/telegramTestPackage#3]

**Comment by nitogel** [comment]
hello world

**Comment by nitogel** [comment]
- [ s] sdfg

- [ ]

**Comment by nitogel** [comment]
- [x] adsfdsf
- [x]  sd

**Comment by nitogel** [comment]
![image](https://cloud.githubusercontent.com/assets/10072011/23745370/8e9c2872-04c0-11e7-8e16-2dda3d05f8e2.png)
